name: pokemon_app
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Defines the version and build number for the application.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  google_fonts: ^5.0.0
  url_launcher: ^6.1.5  # Asegúrate de usar la última versión disponible
  flutter_svg: ^2.0.16
  icon_broken: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
